apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubecustos-collector
  namespace: default
  labels:
    app: kubecustos-collector

spec:
  selector:
    matchLabels:
      app: kubecustos-collector

  template:
    metadata:
      labels:
        app: kubecustos-collector

    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      serviceAccountName: kubecustos-collector

      containers:
        - name: collector
          image: phx.ocir.io/axhke2ki3z5r/kubecustos:1.8.9.3
          imagePullPolicy: IfNotPresent

          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            seccompProfile:
              type: Unconfined

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: SLACK_WEBHOOK_URL

            - name: DEBUG
              value: "1"

          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true

            - name: host-cgroup
              mountPath: /host/sys/fs/cgroup
              readOnly: true

            - name: bpf-fs
              mountPath: /sys/fs/bpf

            - name: kernel-debug
              mountPath: /sys/kernel/debug

            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true

            - name: host-run
              mountPath: /host/run
              readOnly: true

      volumes:
        - name: host-proc
          hostPath:
            path: /proc

        - name: host-cgroup
          hostPath:
            path: /sys/fs/cgroup

        - name: bpf-fs
          hostPath:
            path: /sys/fs/bpf

        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug

        - name: lib-modules
          hostPath:
            path: /lib/modules

        - name: host-run
          hostPath:
            path: /run
